name: Run crm autotests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Authorization'
        default: 'TestAuthorization'
        type: choice
        options:
          - TestAuthorization
          - TestPrlistDBF

jobs:
  run_crm_autotests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run TestPrlistDBF
        if: ${{github.event.inputs.test_type == 'TestPrlistDBF'}}
        run: pytest -n auto --env=prod tests/file_processing/product_import_from_files/test_prlist_dbf.py
      - name: Run TestAuthorization
        if: ${{github.event.inputs.test_type == 'TestAuthorization'}}
        env:
          LOGIN: ${{secrets.LOGIN}}
          PASSWORD: ${{secrets.PASSWORD}}
        run: pytest --alluredir=allure-results --env=dev tests/base/test_authorization.py

      - name: Upload Allure results  # Загружаем результаты тестов в GitHub Actions
        if: always()  # Загружаем файлы независимо от успеха/неуспеха тестов
        uses: actions/upload-artifact@v4
        with:
          name: allure-results  # Название артефакта
          path: allure-results  # Путь к файлам отчета
  
  generate_report:
    needs: run_crm_autotests
    runs-on: ubuntu-latest
    name: Generate Allure report
    
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          
      - name: Check out repository
        uses: actions/checkout@v4  # Клонируем репозиторий
        with:
          ref: gh-pages  # Клонируем ветку gh-pages
          path: gh-pages  # Указываем путь, куда клонировать
        
      - name: Load Allure results history
        if: always()
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          name: gh-pages
          path: gh-pages
      
      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-results
          allure_results: allure-results
          
      - name: Publish Allure report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
        
        
