name: Run crm autotests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Authorization'
        default: 'TestAuthorization'
        type: choice
        options:
          - TestAuthorization
          - TestPrlistDBF

jobs:
  run_crm_autotests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Firefox
        run: |
          sudo apt update
          sudo apt install firefox-esr
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run TestPrlistDBF
        if: ${{github.event.inputs.test_type == 'TestPrlistDBF'}}
        run: pytest -n auto --env=prod tests/file_processing/product_import_from_files/test_prlist_dbf.py
      - name: Run TestAuthorization
        if: ${{github.event.inputs.test_type == 'TestAuthorization'}}
        env:
          LOGIN: ${{secrets.LOGIN}}
          PASSWORD: ${{secrets.PASSWORD}}
        run: pytest --env=dev tests/base/test_authorization.py
      
