name: Run crm autotests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Authorization'
        default: 'TestAuthorization'
        type: choice
        options:
          - TestAuthorization
          - TestPrlistDBF

jobs:
  run_crm_autotests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run TestPrlistDBF
        if: ${{github.event.inputs.test_type == 'TestPrlistDBF'}}
        run: pytest -n auto --env=prod tests/file_processing/product_import_from_files/test_prlist_dbf.py
      - name: Run TestAuthorization
        if: ${{github.event.inputs.test_type == 'TestAuthorization'}}
        env:
          LOGIN: ${{secrets.LOGIN}}
          PASSWORD: ${{secrets.PASSWORD}}
        run: pytest --alluredir=allure-results --env=dev tests/base/test_authorization.py
      - name: Save allure-results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention_days: 1

  generate_report:
    needs: [ run_crm_autotests ]
    runs-on: ubuntu-latest
    name: Generate report

    steps:

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - run: |
          sudo apt-get install default-jre-headless
          wget https://github.com/allure-framework/allure2/releases/download/2.34.0/allure_2.34.0-1_all.deb
          sudo dpkg -i allure_2.34.0-1_all.deb
          sudo apt-get install -f
          allure --version
      - name: Download allure-results
        uses: actions/download-artifact@v4
      - run: allure generate -c allure-results -o _site
      - name: Save generated report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
          retention_days: 1

  publish_report:
    needs: [ generate_report ]
    runs-on: ubuntu-latest
    name: Publish report

    steps:
      - name: Download generated report
        uses: actions/download-artifact@v4
      - name: Upload Pages artifacts
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4