name: Run crm autotests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Authorization'
        default: 'TestAuthorization'
        type: choice
        options:
          - TestAuthorization
          - TestPrlistDBF

jobs:
  run_crm_autotests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1
        
      - name: install dependencies
        run: pip install -r requirements.txt
        
      - name: Run TestPrlistDBF
        if: ${{github.event.inputs.test_type == 'TestPrlistDBF'}}
        run: pytest -n auto --env=prod tests/file_processing/product_import_from_files/test_prlist_dbf.py
        
      - name: Run TestAuthorization
        if: ${{github.event.inputs.test_type == 'TestAuthorization'}}
        env:
          LOGIN: ${{secrets.LOGIN}}
          PASSWORD: ${{secrets.PASSWORD}}
        run: pytest --alluredir=allure-results --env=dev tests/base/test_authorization.py
        
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

  publish-report:
    needs: [ run_crm_autotests ]
    runs-on: ubuntu-latest
    name: Generate report

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages 
          
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          
      - name: Install Allure
        run: |
          sudo apt-get install default-jre-headless
          wget https://github.com/allure-framework/allure2/releases/download/2.34.0/allure_2.34.0-1_all.deb
          sudo dpkg -i allure_2.34.0-1_all.deb
          sudo apt-get install -f
          allure --version
          
      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results
          
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results
          
      - name: Publish Allure report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
